# Generated by Django 4.2.5 on 2023-10-26 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mejores_peliculas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='sinopsis',
            field=models.TextField(),
        ),
    ]
