# Generated by Django 4.2.5 on 2023-10-31 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mejores_peliculas', '0003_director_comentario_alter_pelicula_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='anio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
